### ISSUE TITLE
TypeScript compiler error: Cannot find module

### ISSUE THREAD

**Issue by Anruin** [ceolter/ag-grid-ng2#46]
Hello,

After updating from AgGrid 5.4.0 to 6.0.x running `tsc` gives me following errors:

```
node_modules/ag-grid-ng2/main.d.ts(5,15): error TS2307: Cannot find module './lib/AgFrameworkComponent'.
node_modules/ag-grid-ng2/main.d.ts(6,15): error TS2307: Cannot find module './lib/AgRendererComponent'.
node_modules/ag-grid-ng2/main.d.ts(7,15): error TS2307: Cannot find module './lib/AgEditorComponent'.
node_modules/ag-grid-ng2/main.d.ts(8,15): error TS2307: Cannot find module './lib/AgFilterComponent'.
```

The problem is that files are actually named with small letter "a" and import string has capital "A". I've manually changed it and it seems to fix the error. I can confirm the error in Bash for Windows (I think same will happen on Ubuntu), on MacOS it works well as it is.

Thanks.

**Comment by seanlandsman** [comment]
Yes, you're right - I'm not entirely sure how I missed this (and will investigate why our examples project doesnt report it). I'll do a new release today to resolve this

thanks

**Comment by seanlandsman** [comment]
I have fixed this and will target a release for later today to resolve this.  I'm unable to reproduce this on win 10 with bash for Windows, which is strange and I'm a little surprised it works on the mac!

Anyway, I'll update this thread once we do the release

**Comment by Anruin** [comment]
Thanks, @seanlandsman 
I'm also surprised, but it just works on Mac. No errors on same project. Maybe I have some weird setup there or here on Windows machine. Anyway, it's good to have response and fix so fast. Thanks again, guys!

**Comment by seanlandsman** [comment]
6.0.4 should fix this - let us know if it doesnt

thanks

**Comment by Anruin** [comment]
I confirm that it works now. Thanks.
