### ISSUE TITLE
AoT compilation (v6.1.1) throws error "Property 'gridReady' does not exist on type 'AgGridNg2'"

### ISSUE THREAD

**Issue by basvandenberg** [ceolter/ag-grid-ng2#59]
After updating to 6.1.1 and using `AgGridModule.withAotSupport()` I get the following error when running `ngc`:

```
Error at /path-to-repo/myComponent.component.ngfactory.ts:247:53: Property 'gridReady' does not exist on type 'AgGridNg2'.
```

The same error is thrown for all ag-grid-ng2 property and event bindings used in my templates: `rowData`, `columnDefs`, `modelUpdated`, ... .

I might be forgetting something, but I can't figure out what that is.

**Comment by seanlandsman** [comment]
I've found the problem and will be releasing a new version for this soon - thanks for reporting it

**Comment by seanlandsman** [comment]
I've released ag-grid-ng2@6.1.4-beta for this - can you please give it a go and let me know if it resolves it?

**Comment by basvandenberg** [comment]
Works, compiles without errors now, thanks!

**Comment by seanlandsman** [comment]
great, thanks - I've just released 6.1.4, which includes this fix

thanks
