### ISSUE TITLE
Any chance you can upgrade to work with angular 2.0 RC? 

### ISSUE THREAD

**Issue by fripp0971** [ceolter/ag-grid-ng2#9]
Need to separate out the angular2/core into @angular/core instead

Update - I just changed the refs for angular2/core in the js files to @angular/core and everything works as expected.

So MY copy works, just not the one on npm

Thanks again for an amazing grid.

**Comment by ceolter** [comment]
not working for me :(

i replaced my package.json in ag-grid-ng2 project to:

```
  "peerDependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "ag-grid": "4.1.x"
  }
```
and then change my import to:
```
import {Component, EventEmitter, ViewEncapsulation, ElementRef} from '@angular/core';
```

which then gave the compile error when running gulp of:
```
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(39,88): error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(99,42): error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(174,33): error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,123): error TS2304: Cannot find name 'Map'.
.......<<< and many more similar errors >>>
```

any help???

**Comment by fripp0971** [comment]
Hmmm.. Not sure if it matters but I was using RC0 not 1.  Also, I left my
rxjs at beta 5 /2 and didn't upgrade that. Up to beta 16 of Angular 2 they
had 5/2 as a dependency so I figured leave that in place. As far as the
Promise goes, it comes from es6-shim on mine.
On May 4, 2016 3:57 AM, "Niall Crosby" <notifications@github.com> wrote:

not working for me :(

i replaced my package.json in ag-grid-ng2 project to:

  "peerDependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "ag-grid": "4.1.x"
  }

and then change my import to:

import {Component, EventEmitter, ViewEncapsulation, ElementRef} from
'@angular/core';

which then gave the compile error when running gulp of:

C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(39,88):
error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(99,42):
error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/application_ref.d.ts(174,33):
error TS2304: Cannot find name 'Promise'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15):
error TS2304: Cannot find name 'Map'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16):
error TS2304: Cannot find name 'Map'.
C:/development/workspace/ag-grid-ng2/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,123):
error TS2304: Cannot find name 'Map'.
.......<<< and many more similar errors >>>

any help???

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/ceolter/ag-grid-ng2/issues/9#issuecomment-216770909>

**Comment by fripp0971** [comment]
For the Promise, I dragged this ref to the top of my bootstrap file

/// <reference path="../node_modules/@angular/platform-browser-dynamic/src/facade/promise.d.ts" />

**Comment by ceolter** [comment]
did you leave something out above?

**Comment by fripp0971** [comment]
It looks like it was stripped out the first time. Here is what I included:
`
/// <reference path="../node_modules/@angular/platform-browser-dynamic/src/facade/promise.d.ts" `

**Comment by ceolter** [comment]
cool, will try again in a few hours, busy for the next while :(

**Comment by abdulhaq-e** [comment]
I made it work. The typings for `core-js` need to be referenced. They can be added to the gulp file:

```
var tsResult = gulp
        .src([
           'typings/main/ambient/core-js/index.d.ts',
            'src/**/*.ts'
        ])
```

I'm not sure though how to implement it in the build process because for testing I simply copied and pasted `index.d.ts`. You can find it [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/core-js/core-js.d.ts)

**Comment by ceolter** [comment]
fixed it.
